### ISSUE TITLE
Possible to edit notes inside of the browser?

### ISSUE THREAD

**Issue by anthrolisp** [karlicoss/promnesia#111]
This looks incredible!
Is it possible to edit the notes inside of the browser?
Thanks!

**Comment by karlicoss** [comment]
Hey, thanks! :) 
Not possible at the moment, and it's far out of the scope at least for some near future. The biggest difficulty is that Promnesia doesn't know about any tokens (so can't access APIs to write data back), and can't access your filesystem (as any other browser extension).

However, judging by your nickname, you're interested in Emacs and possibly org-mode notes? :) Then a faster edit cycle is kind of in my plans:

- you already can jump to the file in Emacs from Promnesia, if you use [this script](https://github.com/karlicoss/open-in-editor#readme)
- soon I'll add a fix so you can also jump straight to the line containing the note (or by using note `ID`)
- and once some sort of realtime indexing is implemented, promensia would be able to watch for changes and instantly reflect it in the interface https://github.com/karlicoss/promnesia/issues/20

So you'd still have to use Emacs (or any other editor) to edit the notes, but it will hopefully be instantly reflected in Promnesia.

**Comment by karlicoss** [comment]
Still way out of scope of promnesia, so I'm closing this; I've posted an update about better support for more frequent indexing thoug https://github.com/karlicoss/promnesia/issues/20#issuecomment-724453911
