### ISSUE TITLE
Make python-magic optional when file is installed with python bindings

### ISSUE THREAD

**Issue by mjsir911** [karlicoss/promnesia#116]
Hi,

This is already mentioned in `setup.py` unders `DEPS_INDEXER`:
```
    # TODO could be optional?
    'python-magic', # for detecting mime types
```

But the `python-magic` module should not be required when the file package is installed with python bindings.

**Comment by karlicoss** [comment]
Thanks! My rationale for thinking of making it optional was just because it's only needed for certain indexers and the less required dependencies, the better; but I didn't realize sometimes python bindings are packaged by default. Which distro are you using out of curiosity?

**Comment by mjsir911** [comment]
I'm using Gentoo which lets me pick and choose how & with what features I want packages to be built

```
$ equery u sys-apps/file
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sys-apps/file-5.37-r1:
 U I
 - - python                   : Add optional support/bindings for the Python language
 - - python_targets_python3_6 : Build with Python 3.6
 + + python_targets_python3_7 : Build with Python 3.7
```

Right now I have `file` without python bindings because both `python-magic` and file can't be installed at the same time, but the little testing I did let me do `import magic` without `python-magic` installed and with `file` installed with python bindings

**Comment by karlicoss** [comment]
Finally got to tick it off! Merged and will be in the next release (hopefully soon-ish)
