### ISSUE TITLE
'hug' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by mjsir911** [karlicoss/promnesia#118]
Now this is a weird one where I don't know how much of the problem is my machine:

```
$ promnesia serve
[INFO    2020-06-28 14:25:44,033 promnesia server.py:305] Running server: ['python3', '-m', 'hug', '-p', '13131', '-f', '/usr/lib/python3.7/site-packages/promnesia/server.py']
[INFO    2020-06-28 14:25:44,033 promnesia server.py:305] Running server: ['python3', '-m', 'hug', '-p', '13131', '-f', '/usr/lib/python3.7/site-packages/promnesia/server.py']
/usr/lib/python-exec/python3.7/python3: No code object available for hug.__main__; 'hug' is a package and cannot be directly executed
```

And doing the same command manually gives me the same problem:
```
$ python3 -m hug
/usr/lib/python-exec/python3.7/python3: No code object available for hug.__main__; 'hug' is a package and cannot be directly executed
```

Now my temporary solution to this is removing the `python3 -m` from the command, because a `hug` executable exists and does things properly:
```
$ hug
Error: must define a file name or module that contains a Hug API
```

Now the question is basically: do other systems have `hug` in the `$PATH`? Am I doing something weird where I can't execute hug with `python3 -m hug` on my (gentoo) system?

**Comment by karlicoss** [comment]
Huh, interesting. As far as I understand, it's preferable to use `python3 -m` because the path where Python puts binaries might not be on PATH. Maybe I should make it defensive just in case -- if `python3 -m` fails, simply try to call `hug`.

**Comment by mjsir911** [comment]
That is my understanding too, but I've slowly been weaning off of using `-m` for things (`python -m venv` -> `virtualenv`).

It looks like on the [hug documentation](https://github.com/hugapi/hug) that it is consistently used with just `hug`.

**Comment by mjsir911** [comment]
Alternatively, you might want to just look in to what `hug` is doing in the `__main__`. Because you are just calling python from python, you might want to just use the `hug.development_runner.hug` function(?) which accepts all the same flags as the command line:

```
hug.development_runner.hug(port=port, file=__file__, silent=quiet)
```

Although this doesn't seem as documented in the hug documentation, and I don't know the implications of using a file in the same python process twice with hug.

**Comment by karlicoss** [comment]
> It looks like on the hug documentation that it is consistently used with just hug.

Yeah, it's kind of reasonable, in 95% of cases `.local/bin` (which I think is the default path where Python installs executables) is in `PATH`, so everything works as expected. But the 5% of cases when it isn't (especially typical of CI not to have it) are annoying, so I got used to `python3 -m`. I guess another reason is that it's more consistent in terms of Python version used (although it's not a big issue for most users).

> Alternatively, you might want to just look in to what hug is doing in the __main__

Yeah, thanks, I'll take a look!

**Comment by karlicoss** [comment]
Ugh! Auto-closed, but either way it will make it into new release soon, so hopefully won't be a problem anymore. Thanks for the `development_runner` tip @mjsir911 !
