### ISSUE TITLE
Do not specify DB option when installing server if no path is provided

### ISSUE THREAD

**Issue by buckley-w-david** [karlicoss/promnesia#121]
This is likely a problem with other methods, but I encountered it with systemd and so will just talk about the problem in that context.

In the process of templating the unit file, if a db path is not provided, the config will turn out something like this:
```
[Unit]
Description=Promnesia browser extension backend

[Install]
WantedBy=default.target

[Service]
ExecStart=/home/{user}/.local/bin/promnesia serve --db None --timezone Canada/Eastern --port 13131
Type=simple
Restart=always
```
The problem with this is that `None` argument for the db there is just interpreted as the string `"None"` instead of the object `None` when the server is started, and so all the conditionals with `db is None` fail, and when the server attempts to load the db it throws an AssertionError because it can't find the db at path `"None"`

I fixed this in my local setup by deleting the `--db None` argument from the unit file, but when an argument is None it should probably just be omitted from the unit file entirely.

**Comment by karlicoss** [comment]
Thanks, fixed! Added implicit db detection recently, so haven't spotted this issue.
