### ISSUE TITLE
Not compatible with iOS Firefox mobile 

### ISSUE THREAD

**Issue by alexriabtsev** [karlicoss/promnesia#128]
Trying to install Promnesia extension for Firefox on my iPhone and getting message:

- This add-on is not compatible with this browser. Try installing it on Firefox for desktop.

Firefox 27.0 (18428)
iOS 14.0
Model name iPhone SE
Model number MP7T2LL/A

**Comment by karlicoss** [comment]
Hi! Thanks for reporting. Hmm, this is unfortunate. I don't have an iphone to test, but I've done quick googling, and apparently [iOS firefox doesn't support web extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_for_iOS#Addons) :(

I'll keep the issue open so I remember to update the readme.

**Comment by alexriabtsev** [comment]
that's pity :(

**Comment by alexriabtsev** [comment]
#130 PR created
