### ISSUE TITLE
Show database error message in the extension UI

### ISSUE THREAD

**Issue by alexriabtsev** [karlicoss/promnesia#129]
Just installed Promnesia extension for my Firefox on macOS and launched server (finally got it working -> the process is not easy and straightforward).

But there is no luck saving URLs. Every page I'm visiting is marked with:
ERROR: NetworkError when attempting to fetch resource.

However I see Promnesia server running at 13131 port and Firefox extension says it can connect to backend:
Success! {"db":null,"version":"0.11.20200605"}

How can I get it working?

**Comment by alexriabtsev** [comment]
FIXED
just changed the path in config.py

Figured out:
there is two different paths:
`/Users/ral/Library/Application Support/promnesia/promnesia.sqlite` and `/Users/ral/.local/share/promnesia/promnesia.sqlite`

Index works with one path and server running with another one. I copied the db to another directory and got extension working. Now need to figure out where is the config error.

**Comment by karlicoss** [comment]
Hi! Sorry it wasn't straightforward, I don't have macos, so basically working blind here! :)

> ERROR: NetworkError when attempting to fetch resource.
> However I see Promnesia server running at 13131 port and Firefox extension says it can connect to backend

Yeah, I can see it's confusing, `db: null` indicates a problem, but it's pretty cryptic. There is a [todo](https://github.com/karlicoss/promnesia/blob/7435fc5d0b5821cc0299c5575b92be86cf12c65b/src/promnesia/server.py#L175-L177) for it. I guess I could return `db_path: {error: "Error message"}`, at least it would be visible to the user.

> there is two different paths:
> /Users/ral/Library/Application Support/promnesia/promnesia.sqlite and /Users/ral/.local/share/promnesia/promnesia.sqlite

Hmm, that's odd! The first path looks correct, I believe this is `user_data_dir` on OSX: 
https://github.com/karlicoss/promnesia/blob/31df71e07a684c4ef41debc916bc3e04861072a4/src/promnesia/common.py#L478-L479

But not sure how you ended up with `.local/share`, don't think I hardcoded it anywhere in the code. Can you share the commands you're use to index and run the server? Also the config if you don't mind. Thanks!

**Comment by alexriabtsev** [comment]
You may ask me to test whatever you need for macOS (sorry, can't present a macbook to you, yet ;) )

**Comment by karlicoss** [comment]
Implemented proper error handling & display in the UI here https://github.com/karlicoss/promnesia/pull/164
Will be in the next release!

**Comment by karlicoss** [comment]
P.S. all released (+ extension now works even without the backend), so hopefully you can try it out!
