### ISSUE TITLE
'local' visits aren't available for filtering in the sidebar

### ISSUE THREAD

**Issue by alexriabtsev** [karlicoss/promnesia#132]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/8425396/87271883-3426dc80-c4dd-11ea-939e-715d501c94c8.png">
I've visited a page and marked visited in Promnesia extension. But it is not searchable (search is really buggy!) and shows all (0) - see screenshot above.

**Comment by karlicoss** [comment]
Thanks for reporting! Would be great if you could share a bit more context, e.g. which URL exactly you visited, what have you searched exactly, this helps :)

But anyway, I think I know what you mean:

- `all (0) `-- yeah, at the moment it only picks visits 'with contexts': https://github.com/karlicoss/promnesia/blob/8aff1b8e8576241acc36fcaf54eb0442ac28b37c/extension/src/sidebar.js#L337 Don't remember why exactly, need to double check this and maybe process all visits.
- by "not searchable" -- you mean that it doesn't show up when you search by URL? This also might happen, at the moment search is within the 'normalised' URL and the context, so it might not find exact URL match. Agree though that ideally it should, this bit needs to be thought thorough better https://github.com/karlicoss/promnesia/blob/8aff1b8e8576241acc36fcaf54eb0442ac28b37c/src/promnesia/server.py#L216-L218

**Comment by alexriabtsev** [comment]
@karlicoss the URL doesn't matter really 'cause it is the same with all URLs ;)

how can I get cotexts? I now managed only to index my blog posts which are github repo. 
history from FF/Chrome?

**Comment by karlicoss** [comment]
I've released updated Firefox extension, search should work much better with the in-browser visits now! Also works without the backend so hopefully will be easier to try out.

Feel free to reopen if you still have any issues!
