### ISSUE TITLE
No results in "search around"

### ISSUE THREAD

**Issue by Ingvar33** [karlicoss/promnesia#133]
When I click on the date and time link (), a new tab opens with the `moz-extension://05c8243a-4bbc-46f2-bc5a-77835c2a1501/search.html?utc_timestamp=1595473138` and always "Found 0 visits".

Use Linux Mint, Firefox 78, Chrome 84.

Повторю на русском, а то у меня не очень с английским. 
Когда нажимаю ссылку дата/время "search around", то открывается новая вкладка, как как при нажатии кнопки "Search" и ничего не находит, всегда "Found 0 visits".
В Firefox и в Chrome поведение одинаковое.

Log output. Подозрительные ? вместо даты в SELECT.
```
[INFO    2020-07-23 12:47:35,381 promnesia server.py:129] url: http://dummy.org
[INFO    2020-07-23 12:47:35,381 promnesia server.py:132] normalised url: dummy.org
[INFO    2020-07-23 12:47:35,382 promnesia server.py:138] query: SELECT visits.norm_url, visits.orig_url, visits.dt, visits.locator_title, visits.locator_href, visits.src, visits.context, visits.duration 
    FROM visits 
    WHERE strftime(?, datetime(visits.dt)) - ? BETWEEN ? AND ?
[DEBUG   2020-07-23 12:47:35,386 promnesia server.py:143] got 0 visits from db
[DEBUG   2020-07-23 12:47:35,386 promnesia server.py:154] responding with 0 visits
127.0.0.1 - - [23/Jul/2020 12:47:35] "POST /search_around HTTP/1.1" 200 80
```

**Comment by karlicoss** [comment]
Привет! Я зарелизил новую версию (Firefox уже, Chrome скоро должна зааппрувиться), в ней есть поддержка для search around в том числе для истории внутри браузера. Оно теперь работает даже без бэкенда, так что должно быть легко проверить.

P.S. знаки вопроса -- это нормально (правда выглядит пугающе, да), это [prepared statements](https://www.sqlite.org/c3ref/bind_blob.html)

Баг закрываю, но если все еще есть проблема, переоткрывай -- без проблем :)
