### ISSUE TITLE
sidebar sometimes hides behind a nagbar

### ISSUE THREAD

**Issue by koo5** [karlicoss/promnesia#146]
![image](https://user-images.githubusercontent.com/114276/96950805-6f2ca900-14eb-11eb-8308-50c49619e302.png)

**Comment by karlicoss** [comment]
Yeah, I guess it's possible. Although such banners are pretty invasive by design, so not sure if it's worth it to spend effort out-competing them. But happy to accept a patch if there is a simple fix.

**Comment by karlicoss** [comment]
Closing in favor of https://github.com/karlicoss/promnesia/issues/102, easier to keep track and test when it's in the same issue
