### ISSUE TITLE
OUTPUT_DIR not being observerd?

### ISSUE THREAD

**Issue by bs** [karlicoss/promnesia#148]
Hey! Just working my way through configuring.

I notice that:

1. It seems that `OUTPUT_DIR` as specified in the config isn't written to by `serve`?
2. There is currently no way to specify a config when running `serve`?
3. I can see visits logged in the sidebar, but when I click through to one I see:

<img width="616" alt="Screen Shot 2020-10-24 at 5 46 35 PM" src="https://user-images.githubusercontent.com/68/97096423-f9c2f480-1620-11eb-9e89-25a83ccf9a35.png">

Am I missing something? Thanks for your work! <3

**Comment by koo5** [comment]
Hi.

Only indexer writes anything. Serve just reads.
Try my PR for some added helpful logging.

**Comment by karlicoss** [comment]
1. Yep, indeed, as @koo5 mentioned, `serve` command only reads the index and doesn't write anything
2. `serve` doesn't read the same config at the moment, it takes `--db` as a command line argument. 
    
    I guess I need to do a couple of things:

    - add the default config path (e.g. `~/.config/promnesia/config.py`)
    - make `promnesia serve` use its settings from the config 

   That way once you put the config in the right location, you can just run `promnesia index` and `promnesia server` without any arguments!

    In the meantime, see https://github.com/karlicoss/promnesia/issues/140#issuecomment-716889516, I just responded to someone with a similar problem! TLDR, the easiest is probably just to comment out `OUTPUT_DIR` from the config and run `promnesia index` again -- it will just use the default path.

3. Most likely, you've clicked on a 'local' visit (e.g. your chrome/firefox history), it's not supported by `search around` yet

**Comment by karlicoss** [comment]
Hi, I just released a new version which in particular supports working without the backend + I've updated troubleshooting doc which should help you nail down the issue. Feel free to reopen if you still have difficulties setting up!
