### ISSUE TITLE
extension: websites on which 'mark visited' is broken

### ISSUE THREAD

**Issue by karlicoss** [karlicoss/promnesia#168]

**Comment by sopoforic** [comment]
On https://www.comic-rocket.com, the navbar gets broken.

Before:

![2022-03-13 15 23 34 www comic-rocket com 135a21aad7c3](https://user-images.githubusercontent.com/78205/158075676-9b37a320-fe74-4f16-a801-de850544b688.png)

After:

![2022-03-13 15 23 18 www comic-rocket com 907b95dddb49](https://user-images.githubusercontent.com/78205/158075680-17b974da-cfd8-4033-957f-35eeea407b67.png)

**Comment by hpfr** [comment]
The nav bar for my Nextcloud instance breaks. Here's a more public example:

https://nixpk.gs/pr-tracker.html?pr=160343

![image](https://user-images.githubusercontent.com/44043764/160298523-72247a85-1ceb-415b-a2fc-47bc94a45a69.png)

I mentioned on Zulip that a CSS reset stylesheet like https://github.com/necolas/normalize.css might be helpful here. I believe [Tridactyl](https://github.com/tridactyl/tridactyl) does something similar with https://cleanslatecss.com for its link hinting.

**Comment by sopoforic** [comment]
In Vivaldi, a lot of times pointing at a highlighted link will make the popup rapidly flicker in and out of existence, with no obvious way to make it stop. I found that starting a capture with Flameshot reliably makes it stop, which is a bit mysterious.

https://user-images.githubusercontent.com/78205/164471626-ac03486d-053d-4d10-8ab7-0c52830c5b68.mp4

**Comment by sopoforic** [comment]
The [github notifications page](https://github.com/notifications) doesn't behave nicely:

![2022-06-16_11-49](https://user-images.githubusercontent.com/78205/174112790-5962fd03-96fa-4d66-863b-2f5feb90fb05.png)

The number of notifications gets collapsed over to the repo name. Also, I can't seem to get promnesia to exclude all of these links at once. Putting `/github\.com/notifications.*/` in the exclusions box doesn't seem to work, so I guess it doesn't support regular expressions.

**Comment by karlicoss** [comment]
this should get resolved with https://github.com/karlicoss/promnesia/issues/341
