### ISSUE TITLE
can't figure out why nothing is being indexed

### ISSUE THREAD

**Issue by hanoii** [karlicoss/promnesia#175]
Hi,

I wanted to try the tool. I went ahead and installed the server and run it as well the chrome extension. I see Posts to /visits and queries on the log but I always get no results. I haven't added any sources as I wanted to initially try it only for tracking visited web pages, but there seems to be none.

I run index several times as well. I browsed the sqlite database and it's empty and I see no valuable error anywhere.

Any clues or am I missing something? I installed everything through `pip3`

**Comment by karlicoss** [comment]
Hi! Thanks for checking it out!
If you haven't added any sources to `config.py` (i.e. the backend/server), then it's expected that there would be nothing in the database. The server has no access to browser history, it's the extension which 'merges' the history from the browser, and the server into a unified view. However the support for in-browser stuff in previously was somewhat limited. Although it's odd that you don't get any of them, are they not displayed in the sidebar at all for no websites at all?
In any case, I'm almost about to release an updated extension which can work without the backend at all, and has better support for the in-browser stuff, I'll post here when it's available!

**Comment by hanoii** [comment]
Ah, so if I visit something that doesn't get added to the index? I _think_ I might saw something without much context in the tab, only as local, but without any info, and then I cannot search.

So if I want this to index all of my visits for later searching, that's not an intended use case?

Thanks!

**Comment by karlicoss** [comment]
Yeah, the main purpose is to allow search & navigation through history over the external sources (because browser history is usually searchable in the browser itself). But the updated version will support proper search over browser visits too for convenience!

Just curious, what's your usecase? I.e. why is the builtin browser history not working for you? Because it's only keeping 90 days of history or something like that?

**Comment by hanoii** [comment]
It normally works.. I just wiped it clean and although it's stored on google (chrome is my main browser) I went surfing for "something else". I'd like something that stores what I visit, maybe even some meta information around it, even how and where I got to the url... and liked the idea of something local, opensource. Searched a bit and came across your tool on HN.

For now, my use case is just a nicer/independent/smarter browsing history

**Comment by karlicoss** [comment]
Ah, yeah! Then you might want to export a Google Takeout, and then use the Takeout datasource in the backend (listed [here](https://github.com/karlicoss/promnesia/blob/c43eef0a74ce5b674fa2272f4d898ac557d44547/doc/SOURCES.org#sources) ).

There is also a script to backup browser history on your computer: https://github.com/karlicoss/promnesia/blob/master/scripts/browser_history.py (it's a bit undocumented, but hopefully straightforward to figure out from `--help`). You can run it every few days, get sqlite history snapshots as outputs, and then it can also be fed into Promnesia as a data source. Also needs a bit more documentation, but you can set up the backups now and the integration later

**Comment by karlicoss** [comment]
FYI: new version is released, so the support for in-browser visits & bookmarks is much better now!

**Comment by karlicoss** [comment]
closing since now docs are better & extension has the mode without backed, but feel free to reopen if something is still not right
