### ISSUE TITLE
Missing `github` source?

### ISSUE THREAD

**Issue by ankostis** [karlicoss/promnesia#194]
From your [big-plan(TM)](https://beepb00p.xyz/myinfra_files/myinfra.svg), i see this data-flow: 

            .--(manual)-->GDPR-archive-->HPI.github.gdpr------.
    GitHub--+                                                 +-->promnesia.github(src)
            '--ghexport-->json-events--->HPI.github.ghexport--'

but promnesia is missing `promnesia.github(src)` module.
Is that on purpose?

**Comment by karlicoss** [comment]
Oh thank you, nice catch! I guess I forgot to implement github module for promnesia!
