### ISSUE TITLE
Keep changelog?

### ISSUE THREAD

**Issue by karlicoss** [karlicoss/promnesia#215]
@ankostis asked for `CHANGELOG.md` or something like that -- I agree! I

So far I've been keeping it in https://github.com/karlicoss/promnesia/releases , but I think best to keep in the repository because release page is a silo, unlike a file in git repo. I started doing it for HPI recently https://github.com/karlicoss/HPI/blob/master/CHANGELOG.md

My personal thoughts:
- I wouldn't want it to be obligatory after every pull request etc -- I think ideally maintainers could summarize (because not all changes worth mentioning in changelog, and sometimes they are scattered across multiple PRs)
- would be still nice to copy it to releases, not so much effort, clean to view and allows to subscribe for RSS or something

**Comment by karlicoss** [comment]
done! https://github.com/karlicoss/promnesia/blob/master/CHANGELOG.org

**Comment by ankostis** [comment]
My idea if maintaining both CHANGES & github-releases is to write noteworthy changes in the first and copy-paste it verbatim  afterwards in the release-page.
