### ISSUE TITLE
URLs in PROPERTY drawers not recognized?

### ISSUE THREAD

**Issue by amoghpj** [karlicoss/promnesia#218]
Hi!
In the following function to get URLs from an orgmode source: https://github.com/karlicoss/promnesia/blob/8eb9ef3ec30ad045bea7a6a4e89e9579b60e0b1c/src/promnesia/sources/org.py#L103 currently only headings or body are tested for the presence of URLs. The property drawers are only tested for time stamps. I have a setup where notes are captured with a :LINK: property with a URL. Is it possible to add a check to loop over the key-value pairs in the property drawers to test for presence of URLS?
I tried to hack this together, and it works for me for now, but is there a correct way of accomplishing this?
```
    if not n.is_root():        
        try:
            propertydraw = '\n'.join(str(v) for v in n.properties.values()) #ugly hack to get values as single string, can iterate over values?
        except Exception as e:
            logger.exception(e)
            yield e
        else:
            yield from iter_urls(propertydraw, syntax='org')        
```

**Comment by karlicoss** [comment]
Hi, yeah this looks good! And yeah I think iterating over values makes sense?

**Comment by hrehfeld** [comment]
I'm also in need of this, please merge to master! :-)

This (using values directly) also seems to work, but I'm using promnesia for the first time, testing required:

``` py
    if not n.is_root():
        try:
            values = n.properties.values()
        except Exception as e:
            logger.exception(e)
            yield e
        else:
            for v in values:
                assert isinstance(v, str), repr(v)
                yield from iter_urls(str(v), syntax='org')

```

Tell me if a PR would be helpful using this code.

**Comment by karlicoss** [comment]
@hrehfeld this looks good, thanks! Although best to replace `isinstance` assert with if statement though -- for some historic reasons some properties could be int, so this assert might legitimately trigger :) 
https://github.com/karlicoss/orgparse/blob/45b366eb5c23e4149d8bc7a319f10dc74888fe51/orgparse/node.py#L123

For tests -- CI runs tests, could you add a short tests here? https://github.com/karlicoss/promnesia/blob/8eb9ef3ec30ad045bea7a6a4e89e9579b60e0b1c/tests/test_org_indexer.py

Can create a new file under https://github.com/karlicoss/promnesia/tree/8eb9ef3ec30ad045bea7a6a4e89e9579b60e0b1c/tests/testdata/auto/orgs and add a new test, or maybe you can just add a new outline to `file.org` and modify `test_org_indexer` -- up to you!
