### ISSUE TITLE
support specifying config dir through an environment variable

### ISSUE THREAD

**Issue by purarue** [karlicoss/promnesia#226]
Similar to HPI, would be nice if this was possible.

https://github.com/karlicoss/HPI/blob/c1b70cd90e894835d18d9cac04cc1d12724bf3c7/my/core/preinit.py#L8

Else, on mac this puts my config somewhere in /Application Support/ and syncthing cant sync my promnesia config across my computers...

Currently this just uses appdirs without letting the user specify otherwise...

https://github.com/karlicoss/promnesia/blob/137c3d2e685c08a4ead3c2602d7f6cdaf877ed1f/src/promnesia/common.py#L518-L519

Sort of wished appdirs just used XDG_CONFIG_HOME on mac as well...

do you think `PROMNESIA_CONFIG` works as the name of the environment variable?

Am willing to make a PR at some point soon

**Comment by karlicoss** [comment]
Huh, interesting -- is it something where other apps on macs usually put their configs? Or they just hardcode `$HOME/.config/appname` on OSX?

But it also takes `--config` if you want to solve this short-term https://github.com/karlicoss/promnesia/blob/137c3d2e685c08a4ead3c2602d7f6cdaf877ed1f/src/promnesia/__main__.py#L296

I guess env variable makes sense too though, e.g. in dockerfiles -- if we used `click` already could be a trivial change :)

**Comment by purarue** [comment]
I think GUI applications will often put the config at `~/Library/Application Support`, but CLI apps will often just hardcode `$HOME/.config/appname`

Both `appdirs`-like libraries I've seen have put config in `~/Library/Application Support`, but personally not a fan of that - makes it harder for me to sync dotfiles

I didn't realize this was already using click, it would be pretty easy to add, yeah:

https://github.com/seanbreckenridge/ipgeocache/blob/master/ipgeocache/__main__.py#L13

**Comment by karlicoss** [comment]
I guess if we do add an env variable -- maybe best to agree it would be 'config directory', just in case? 
Could change the semantics of `--config` as well, and it could be backwards compatible as well, just by determining if it got passed a `.py` file or a directory

**Comment by purarue** [comment]
specifying either the config directory or the file is fine with me

I think its typical for tools to specify the directory instead of the file, because it makes it more extendable for the future -- theres a possibility to split config among multiple files if thats wanted. Currently we're only using `config.py` but maybe in the future if this is communicating with some backend on the internet on some VPS, and that needs extensive config, it could go in `hosts.py` instead

Though, since this is using python as config, you could always pull things from the environment, or just import from a relative file -- so the concern isn't as prominent

Either works here, depends on if you expect it to expand I guess?
