### ISSUE TITLE
'Europe/Berlin' object has no attribute 'key'

### ISSUE THREAD

**Issue by hrehfeld** [karlicoss/promnesia#249]
On git bc9d9034aa7d83c12e24c60aac50c965513ef9ae
```
$ scripts/promnesia index
[ERROR   2021-09-22 16:02:49 promnesia common.py:493] 'Europe/Berlin' object has no attribute 'key'
    Traceback (most recent call last):
      File "/home/hrehfeld/projects/ext/promnesia/src/promnesia/common.py", line 491, in get_system_zone
        return tzlocal.get_localzone().key # type: ignore[attr-defined] # mypy stubs aren't aware of api change yet (see https://github.com/python/typeshed/issues/6038)
    AttributeError: 'Europe/Berlin' object has no attribute 'key'
[ERROR   2021-09-22 16:02:49 promnesia common.py:494] Couldn't determine system timezone. Falling back to UTC. Please report this as a bug!
```

Just updated from git to bc9d9034aa7d83c12e24c60aac50c965513ef9ae

It seems that tzlocal is somehow outdated?

**Comment by karlicoss** [comment]
Hi! Did you only do git pull? You need tzlocal version 3.0 now, you can upgrade via `pip3 install --user -U tzlocal`

```
/code/promnesia ✔ ❯ python3 -c 'import promnesia.common as C; print(C.get_system_zone())'                                                                                                                                                         mc 23:06:48
Europe/London
/code/promnesia ✔ ❯ pip3 show tzlocal                                                                                                                                                                                                             mc 23:06:50
Name: tzlocal
Version: 3.0
Summary: tzinfo object for the local timezone
Home-page: UNKNOWN
Author: Lennart Regebro
Author-email: regebro@gmail.com
License: MIT
Location: /home/karlicos/.local/lib/python3.8/site-packages
Requires: backports.zoneinfo
Required-by: promnesia
```

**Comment by krillin666** [comment]
> Hi! Did you only do git pull? You need tzlocal version 3.0 now, you can upgrade via `pip3 install --user -U tzlocal`
> 
> ```
> /code/promnesia ✔ ❯ python3 -c 'import promnesia.common as C; print(C.get_system_zone())'                                                                                                                                                         mc 23:06:48
> Europe/London
> /code/promnesia ✔ ❯ pip3 show tzlocal                                                                                                                                                                                                             mc 23:06:50
> Name: tzlocal
> Version: 3.0
> Summary: tzinfo object for the local timezone
> Home-page: UNKNOWN
> Author: Lennart Regebro
> Author-email: regebro@gmail.com
> License: MIT
> Location: /home/karlicos/.local/lib/python3.8/site-packages
> Requires: backports.zoneinfo
> Required-by: promnesia
> ```

This worked for me, so I think you can close this :+1:

**Comment by hrehfeld** [comment]
Sorry, I checked and at the time tzlocal was only 2.0 in the arch repos (I decided to wait and recheck, but forgot). However, it's at 4.0 now: 

```
$ pacman -Q python-tzlocal
python-tzlocal 4.0.1-1
```

```
[ERROR   2021-10-20 19:40:00 promnesia common.py:493] '_PytzShimTimezone' object has no attribute 'key'
    Traceback (most recent call last):
      File "/home/hrehfeld/projects/ext/promnesia/src/promnesia/common.py", line 491, in get_system_zone
        return tzlocal.get_localzone().key # type: ignore[attr-defined] # mypy stubs aren't aware of api change yet (see https://github.com/python/typeshed/issues/6038)
    AttributeError: '_PytzShimTimezone' object has no attribute 'key'
[ERROR   2021-10-20 19:40:00 promnesia common.py:494] Couldn't determine system timezone. Falling back to UTC. Please report this as a bug!
```
I see no reason that this wouldn't use the system lib, unless your wrapper script does something shady with the paths?

(still on bc9d9034aa7d83c12e24c60aac50c965513ef9ae after git pull)

with python -v:

```
$ scripts/promnesia index 2>&1 | ag tzlocal
# /usr/lib/python3.9/site-packages/tzlocal/__pycache__/__init__.cpython-39.pyc matches /usr/lib/python3.9/site-packages/tzlocal/__init__.py
# code object from '/usr/lib/python3.9/site-packages/tzlocal/__pycache__/__init__.cpython-39.pyc'
# /usr/lib/python3.9/site-packages/tzlocal/__pycache__/unix.cpython-39.pyc matches /usr/lib/python3.9/site-packages/tzlocal/unix.py
# code object from '/usr/lib/python3.9/site-packages/tzlocal/__pycache__/unix.cpython-39.pyc'
# /usr/lib/python3.9/site-packages/tzlocal/__pycache__/utils.cpython-39.pyc matches /usr/lib/python3.9/site-packages/tzlocal/utils.py
# code object from '/usr/lib/python3.9/site-packages/tzlocal/__pycache__/utils.cpython-39.pyc'
# /usr/lib/python3.9/site-packages/tzlocal/__pycache__/windows_tz.cpython-39.pyc matches /usr/lib/python3.9/site-packages/tzlocal/windows_tz.py
# code object from '/usr/lib/python3.9/site-packages/tzlocal/__pycache__/windows_tz.cpython-39.pyc'
```

**Comment by karlicoss** [comment]
hmm looks like it's the issue described here https://github.com/karlicoss/promnesia/issues/253

upd: should be fixed now, if you pull the latest git version!

**Comment by hrehfeld** [comment]
Thanks for the work, I'll try later!

27 Oct 2021 23:53:11 karlicoss ***@***.***>:
