### ISSUE TITLE
OSX.Genieo adware found by Malwarebytes

### ISSUE THREAD

**Issue by llasse** [karlicoss/promnesia#257]
I know this might not be the most proper bug report/issue, because I dont exactly when I tried out promnesia - however, Malwarebytes threw a warning at me that involves Promnesia:
![Bildschirmfoto 2021-11-23 um 23 31 12](https://user-images.githubusercontent.com/33515615/143139568-64e89161-bd0a-4191-85a4-4c435976ddd7.png)

Any ideas how this comes about? Running OSX Mojave (10.14.6, happy to provide more information if I know what is of interest..

**Comment by karlicoss** [comment]
:scream: this is odd.. 
Can you please paste here the contents of file under the Ort column? (I guess it'd be named `promnesia.plist`)?

**Comment by karlicoss** [comment]
hey @llasse any update about it?

**Comment by karlicoss** [comment]
feel free to reopen if it's still an issue
