### ISSUE TITLE
Promnesia no longer available in Mozilla Add-on Store

### ISSUE THREAD

**Issue by pgrosslicht** [karlicoss/promnesia#259]
Hi,

I just wanted to reinstall the extension but noticed that Promnesia seems to be no longer available in the [Mozilla Add-on Store](https://addons.mozilla.org/en-US/firefox/addon/promnesia). Link now just leads to a 404 page and extension can also not be found manually.

Also thanks for the extension!

**Comment by karlicoss** [comment]
Hi, yeah, a reviewer wanted me to update build instructions, I did and then they never responded :( 
I'll try to release a new version soonish I guess

**Comment by iwconfig** [comment]
Seriously, when did this happen? I've been thinking of testing out Promnesia for the last couple of days and today I was just about to get started when I encountered this. goddammit...

How do I install the extension from source in Firefox? I just point firefox to `extension/`?

---

EDIT: yep, well actually the manifest file is in `extension/src`. however, it doesn't show up. I can only access the settings from `about:addons` :(

**Comment by iwconfig** [comment]
I'm eagerly waiting

```bash
$ cat ~/scripts/isPromesiaAddonAvailableYet.sh
#!/bin/bash
# while loop, cronjob or whatever every N unit(s) of time
if [ $(curl -so /dev/null -ILw '%{http_code}' https://addons.mozilla.org/en-US/firefox/addon/promnesia/) == 200 ]; then
    msg='PROMNESIA ADDON IS AVAILABLE! :D'
    zenity --info --text "$msg" 2> >(grep -v GtkDialog >&2) & 
    echo $msg
else
    echo 'no promnesia :('
fi
```

**Comment by rootkea** [comment]
@iwconfig Or you could just subscribe to this Github thread :)

**Comment by iwconfig** [comment]
I'm going mad over here. I'm biting my nails @rootkea! :smile: Btw, I already am subscribed, aren't I? :wink:

**Comment by karlicoss** [comment]
I've submitted a new version, it's awaiting approval now!

**Comment by ankostis** [comment]
> a reviewer wanted me to update build instructions, I did and then they never responded :(

But why did the reviewer disabled the extension?
Was that a security concern?

**Comment by pgrosslicht** [comment]
> But why did the reviewer disabled the extension? Was that a security concern?

Yes, they need to be able to view the code, as per their [guidelines](https://extensionworkshop.com/documentation/publish/source-code-submission/) to be able to review the code. In case of minification like this project is doing you need to provide the original source as well as build instructions so they can make sure that the code you uploaded is actually stemming from the code you gave them to review.

They do suggest not minifying code since there are no advantages when loading times over the internet are not an issue, this might be worth giving a thought as well.

**Comment by karlicoss** [comment]
@ankostis yeah, sort of, this was why it was flagged

> Please take care of the following:
> This version contains minified, concatenated or otherwise machine-generated code. Please provide the original sources, together with instructions on how to generate the final XPI. Source code must be provided as an archive and uploaded using the source code upload field, which can be done during submission or on the version page in the developer hub. 
> Please read through the instructions at https://extensionworkshop.com/documentation/publish/source-code-submission/ .

I attached source code (ugh wish it was possible through API when you publish the extensions), but then they had issues with building (because `npm install` was missing from the instructions), I updated them, but got no response after that, and the extension was disabled :(

@pgrosslicht thanks, good idea -- maybe I should try without the minification! Guess it was just the default webpack does so I never questioned it.

**Comment by karlicoss** [comment]
Ok, after **a lot** of back and forth it's finally back! :) 

I added instructions specifically to point AMO reviewers at next time
https://github.com/karlicoss/promnesia/blob/master/doc/addons-mozilla-org.org

**Comment by iwconfig** [comment]
Awesome! I'm gonna explore this right away. Thank you :)
