### ISSUE TITLE
Doc: missing dependencies: cachew, hug, urlextract

### ISSUE THREAD

**Issue by hrehfeld** [karlicoss/promnesia#263]
I'm running from git and trying to install dependencies as mentionened in https://github.com/karlicoss/promnesia/blob/master/doc/SOURCES.org#extra-dependencies manually.

**Comment by astratagem** [comment]
FWIW, `hug` appears to be abandoned since 2020. It also pins the version of its `falcon` dependency to `2.0.0` which was released around 3 years ago (the latest version of `falcon` is `3.1.0`).

https://github.com/hugapi/hug/issues/894
https://github.com/hugapi/hug/issues/897

**Comment by karlicoss** [comment]
@montchr oh, thanks for reporting, I'll look at the alternatives.

**Comment by karlicoss** [comment]
Switched from hug to fastapi, will run locally and release after a bit https://github.com/karlicoss/promnesia/pull/347/files
