### ISSUE TITLE
How do you access options?!

### ISSUE THREAD

**Issue by practik** [karlicoss/promnesia#265]
I just installed Promnesia 1.0.1 on Firefox 95.0.2. I am not planning to install the backend.

On every webpage I visit, Promnesia's icon is red and overlaid with the word "Type". When I click on it, I get this error message:

    Error: NetworkError when attempting to fetch resource.
    while requesting http://localhost:13131/visits
    check extension options, make sure you set backend or disable it (set to empty string)

I would be happy to do that, but I don't see any way to access the options. There is no link to them from the sidebar, from the contextual menu I get when I right-click on the icon, or from about:addons. How do I get to them?

**Comment by karlicoss** [comment]
![image](https://user-images.githubusercontent.com/291333/147992113-355c4549-03f8-4032-b59e-ea0042c43e35.png)

Hi, on the `about:addons` page you need to click on the ellipsis to access the preferences (same way as for other addons)

**Comment by practik** [comment]
Oh! Funny, I've never accessed the prefs of any extension that way before. Thank you!
