### ISSUE TITLE
RaspberryPi setup breaks 

### ISSUE THREAD

**Issue by 9s-l-s9** [karlicoss/promnesia#273]
Hello, 

trying to install on RapsberryPi for some time now, but I get the following error. Any ideas?

`/home/pi/.local/lib/python3.7/site-packages/promnesia/common.py:491: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzlocal.get_localzone().zone
`

and 

`
[ERROR   2022-02-23 22:59:47 promnesia __main__.py:82] No visits were indexed, something is probably wrong!
NoneType: None
`

Maybe related: #262  #253

Thank you

**Comment by karlicoss** [comment]
Hi! Might be related, but not sure, is this the only warning/error from logs?
Can you paste the output of `pip3 show tzlocal`? If it's version `3.x`, perhaps worth upgrading it to `4.x` (`pip3 install --user -U tzocal`)

Also, could you paste the contents of your Promnesia config? (likely `~/.config/promnesia/config.py`)

And also in the meantime, could you try steps from the [troubleshoot guide](https://github.com/karlicoss/promnesia/blob/master/doc/TROUBLESHOOTING.org#general-notes)? 

Thanks!

**Comment by 9s-l-s9** [comment]
Okay. 
# pip3 show tzlocal
`Name: tzlocal
Version: 4.1
Summary: tzinfo object for the local timezone
Home-page: UNKNOWN
Author: Lennart Regebro
Author-email: regebro@gmail.com
License: MIT
Location: /home/pi/.local/lib/python3.7/site-packages
Requires: pytz-deprecation-shim, backports.zoneinfo
Required-by: promnesia
`

# ~/.config/promnesia/config.py

`
from promnesia.common import Source
from promnesia.sources import auto

'''
List of sources to use.

You can specify your own, add more sources, etc.
See https://github.com/karlicoss/promnesia#setup for more information
'''
SOURCES = [
    Source(
        auto.index,
        # just some arbitrary directory with plaintext files
        '/home/pi/notes/',
    )
]`

I changed the "source" path, because I thought it might be a problem with the example path. 
# Troubleshoot guide
I tried the guide before opening this issue to solve the problem on my own, but to no avail.

**Comment by karlicoss** [comment]
Aha thanks!
`tzlocal` version looks good, so it's warning probably isn't relevant to the promnesia error (but still thanks for posting it, I'll look into it later)

It's odd it's not indexing anything then -- what kinds of files do you have in `/home/pi/notes`? Could you perhaps post the output of `find /home/pi/notes/`? (feel free to filter out in case there are any private ones)

And maybe could you post an example paragraph from one of the files where you would expect Promnesia to extract a URL/visit?

**Comment by 9s-l-s9** [comment]
### Output for find /home/pi/notes/
`
/home/pi/notes/

/home/pi/notes/Nice.txt

/home/pi/notes/Test.md

/home/pi/notes/Hallo.md
`
### File structure
The files are mostly empty, created just for testing.  
"And maybe could you post an example paragraph from one of the files where you would expect Promnesia to extract a URL/visit?" 
Does this mean that notes should have some form of structure? They mostly contain just some strings, but even after adding a URL it still can't index.

**Comment by 9s-l-s9** [comment]
Okay, I am sorry. After some more testing I realized, that the reason was because the URL was not in the right [Markdown](https://github.com/karlicoss/promnesia/issues/273) format. 

It is also a misunderstanding on my site, because I thought, promnesia could work similar to the search in WorldBrain Memex and did not realize that it would just show notes, if they contain the same URL

**Comment by karlicoss** [comment]
ah! What is your format, out of curiosity? Maybe it'd be easy to support it!
But yeah Promnesia and Worldbrain are quite different, what search behaviour did you expect?

**Comment by 9s-l-s9** [comment]
"ah! What is your format, out of curiosity? Maybe it'd be easy to support it!"

It was just markdown with a "normal" url in it that didn't work. 

"But yeah Promnesia and Worldbrain are quite different, what search behaviour did you expect?"

In Worldbrain, if you search for something on a search enigine (e.g. google) it takes the search string and also searches for results from your ressources in Worldbrain. 

I want to do something similar but search in my personal notes (markdown format), when I search for something in Google. This way, I can see, if I have already taken a note  about the topic I am searching for or I could identify relationsship between previous notes and what I am currently searching for.

**Comment by karlicoss** [comment]
Right, I see -- yeah that would be a nice feature, Promnesia could inject results into google search https://github.com/WorldBrain/Memex/issues/281
The main problem at the moment is that it would require a much better search engine, otherwise you might have too many results polluting your normal search results. But one day, would be nice :)
