### ISSUE TITLE
character maps to <undefined>

### ISSUE THREAD

**Issue by mdroidian** [karlicoss/promnesia#274]
**Operating System:** Windows
**Python:** 3.10.2

Doing `promnesia index` on a folder of .md files resulted in multiple `character maps to <undefined>` errors.

They seem to be files with emojis like 🤝 or 🔁 characters like “ instead of "

What might be a good way of dealing with this?

**Comment by karlicoss** [comment]
Hi! 
Hmm I don't know much about Windows, but looks like encoding issue -- could you maybe share a minimal example of a file that triggers indexing issue? Ideally in a zip archive or something like that -- so the original encoding is preserved

**Comment by mdroidian** [comment]
Here you are sir.
[error charmap undefined.zip](https://github.com/karlicoss/promnesia/files/8189349/error.charmap.undefined.zip)

**Comment by karlicoss** [comment]
Thanks! So the files look okay, and the encoding looks like valid UTF8, and they are indexing without problems on my linux.
So I guess I'd need to test it on a windows host to reproduce. Not sure when I'll have time though, how annoying is this for you? Is it a lot of files or just a few?

**Comment by mdroidian** [comment]
~200 files.  Only minor annoyance currently.  

While knowing that not all of my URLS are indexed would be a deal breaker long term, I have a TON of URLs in other sources (like Todoist), so I still need to build out those sources, which will take awhile. 👍

**Comment by mdroidian** [comment]
So I may have found the solution. [Python: Use the UTF-8 mode on Windows](https://dev.to/methane/python-use-utf-8-mode-on-windows-212i)

I can confirm that using `set PYTHONUTF8=1` in Command Prompt, or `$Env:PYTHONUTF8="1"` in PowerShell also seems to fix the error for me. 😊

**Comment by karlicoss** [comment]
ooh, awesome, thanks!
