### ISSUE TITLE
Custom sidebar.css ?

### ISSUE THREAD

**Issue by kvgc** [karlicoss/promnesia#281]
Hi,
Thanks for this amazing project. This is really helpful.
Is there a way to add custom css to the sidebar without having to recompile the entire extension ? That would be a very helpful feature. Some possible use cases would be:  changing font-size of the text, button-size, colors. etc.
Thanks!

**Comment by sopoforic** [comment]
If you open up the extension options, there's a "Style settings (CSS)" section near the bottom which should do what you want.

**Comment by kvgc** [comment]
Thanks. That's exactly what I was looking for!

**Comment by karlicoss** [comment]
closing since seems to be solved, but feel free to reopen @kvgc if you have some specific questions about the custom css!

**Comment by kvgc** [comment]
Hi, 
Just wanted to share my css sidebar configuration (https://gist.github.com/kvgc/9bd2f6a93f0bbcd3bc486a6ca3a96b18) in case anyone is interested. 

![customcss](https://user-images.githubusercontent.com/33746143/158910983-6bc47aae-5985-4bfd-bda9-3972fb001a7e.gif)

Thanks for helping out!

--
kvgc

P.S: Feel free to close this issue again.

**Comment by karlicoss** [comment]
This is awesome! Feel free to create a PR with a link to your configuration/animation as an example, this would be very welcome! :) 

Maybe to this section https://github.com/karlicoss/promnesia/blob/master/doc/GUIDE.org#how-to-customize-extension-style

**Comment by kvgc** [comment]
Awesome. I have created a PR adding this as an example.
