### ISSUE TITLE
Published Docker?

### ISSUE THREAD

**Issue by gerroon** [karlicoss/promnesia#285]
Hi

Is there a working Docker setup on Docker hub? I see couple dockers but I am not sure if they are safe. I personally prefer developer's own version.

**Comment by karlicoss** [comment]
hey, not yet -- I have my custom setup but it'd be hard to share
overall it's pretty tricky to pack in a single docker because of all the dependencies/modules etc
I'll close this issue in favor of an older one -- feel free to follow up there! https://github.com/karlicoss/promnesia/issues/55
