### ISSUE TITLE
Where are the extension settings

### ISSUE THREAD

**Issue by ntevenhere** [karlicoss/promnesia#290]
I can't find the settings page mentioned in [GUIDE.org](https://github.com/karlicoss/promnesia/blob/master/doc/GUIDE.org).

Is it supposed to be in the Add-ons Manager? I can't find the preferences tab.
![screenshot](https://user-images.githubusercontent.com/66701832/163463282-07c0635c-eb2b-4f46-b2f6-1b77fc26d23c.png)

**Comment by karlicoss** [comment]
Hey, here are the instructions (they work for any Firefox extension) -- hope it helps https://browsernative.com/extensions/firefox-extension-options/ Basically, press the ellipsis (...) and you'll find them

**Comment by ntevenhere** [comment]
Oh that was dumb. I don't think I've ever used that ellipsis to access preferences. Extensions that don't have a "Preferences" tab in the manager are usually configurable in the toolbar icon.

**Comment by karlicoss** [comment]
Aah -- I think it's because when the preference page is big, it doesn't fit in the tab in the extension manager anymore so needs to be a separate page
