### ISSUE TITLE
Guarantee pop-up doesn't exit the viewport

### ISSUE THREAD

**Issue by ntevenhere** [karlicoss/promnesia#291]
Links displayed close to the right side margin of the viewport are basically guaranteed to the be unreadable. 

Figure (the black bar is my scrollbar):
![NapesEmptyYid](https://user-images.githubusercontent.com/66701832/163578545-b02399d2-efcd-4d27-b8f9-7085f08efa0e.png)

The extension should calculate if the pop-up will fit in the window, and if not, display the pop-up in the left-hand side, like right click menus work:

![context-men](https://user-images.githubusercontent.com/66701832/163580183-f67c351c-1817-4af6-b23c-21940169a039.png)
![context-menu2](https://user-images.githubusercontent.com/66701832/163580193-05538404-52c4-4971-9531-cb5290e4c9df.png)

**Comment by karlicoss** [comment]
Ah yeah thanks, it happens sometimes. It's kinda tricky to display popups properly in general case, although perhaps this one makes sense to fix
Somewhat related: https://github.com/karlicoss/promnesia/issues/170

**Comment by ntevenhere** [comment]
I wonder if this could be done with CSS. But before that I need to brush up on `@media` queries. I'll get back to you later

**Comment by ntevenhere** [comment]
The CSS idea was delusional but I wrote this little js snippet

```js
var offscreendiff = window.innerwidth - erect.right
if (offscreendiff < 0) { popup.style.left = `${offscreendiff}px` } // if popup goes off-screen, subtract the difference.
```
The snippet should go and _should work_ in [showvisited.js#L291](https://github.com/karlicoss/promnesia/blob/master/extension/src/showvisited.js#L291). I'm not making a pull request because I don't have the build environment set up to test it. The logic _does_ work in the browser console, but idk if it can just be plugged into the extension and work. Feel free to commit my code and fix as needed. The browser console doesn't seem to let me redefine functions, couldn't test in that either.  

After:
![after](https://user-images.githubusercontent.com/66701832/163598823-c53a22e8-befa-4abb-b59c-595c74c769c7.png)
Before:
![JagShirkPulps](https://user-images.githubusercontent.com/66701832/163598907-6e307003-2be7-4ef8-a6d6-ad5272f47994.png)

**Comment by karlicoss** [comment]
Thanks! Yeah, it's unfortunate it's pretty tedious to set up build env, even for me testing is a bit of a pain since browsers are very unfriendly towards dev setups.. And then releasing is also tedious. 
I'll include this with the next batch of changes!

**Comment by karlicoss** [comment]
btw this should get resolved along with this https://github.com/karlicoss/promnesia/issues/341

**Comment by karlicoss** [comment]
new extension is released, shouldn't happen anymore :)
