### ISSUE TITLE
Additional scripts are created

### ISSUE THREAD

**Issue by iaeiou** [karlicoss/promnesia#292]
Hi there,

I've installed Promnesia and everything runs smoothly.

However, additional scripts are created next to `promnesia`:

```
 .local/bin/falcon-bench        | 10 ++++++++++
 .local/bin/falcon-print-routes |  8 ++++++++
 .local/bin/hug                 |  8 ++++++++
 .local/bin/mistletoe           |  8 ++++++++
 .local/bin/promnesia           |  8 ++++++++
 .local/bin/urlextract          |  8 ++++++++
 ```

Could you please explain what are these files for?
I've searched the repo before reporting and found nothing

**Here is the full content of these files:**

**.local/bin/falcon-bench**

    #!/usr/bin/python
    # -*- coding: utf-8 -*-
    import re
    import sys

    from fxa.__main__ import main

    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
        sys.exit(main())

**.local/bin/falcon-print-routes**

    #!/usr/bin/python3
    # -*- coding: utf-8 -*-
    import re
    import sys
    from falcon.cmd.print_routes import main
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
        sys.exit(main

**.local/bin/hug**

    #!/usr/bin/python3
    # -*- coding: utf-8 -*-
    import re
    import sys
    from hug import development_runner
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
        sys.exit(development_runner.hug.interface.cli())

**.local/bin/mistletoe**

    #!/usr/bin/python3
    # -*- coding: utf-8 -*-
    import re
    import sys
    from mistletoe.__main__ import main
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
        sys.exit(main())

**.local/bin/urlextract**

    #!/usr/bin/python3
    # -*- coding: utf-8 -*-
    import re
    import sys
    from urlextract import _urlextract_cli
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
        sys.exit(_urlextract_cli())

They are all very similar to the main `promnesia` script:

**.local/bin/promnesia**

    #!/usr/bin/python3
    # -*- coding: utf-8 -*-
    import re
    import sys
    from promnesia.__main__ import main
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
        sys.exit(main())

I can provide the notes of my installation process.

Thank you for your time
Promnesia is a wonderful piece of software!

**Comment by karlicoss** [comment]
Hi! So this is normal, basically some of promnesia's dependencies come with their binaries because they can also be used as 'tools', not just libraries
https://github.com/karlicoss/promnesia/blob/65320681b875978fe3ac64bce5c42d45695159cd/setup.py#L31-L76

e.g. `hug` binary is the development server for `hug` library

`mistletoe` has interactive mode for markdown rendering: https://github.com/miyuchina/mistletoe#mistletoe-interactive-mode

and so on

It would be nicer if there was a way to depend on something in python which doesn't drag binaries, but as far as I know, it's not possible unfortunately

**Comment by iaeiou** [comment]
Thanks a lot for this explanation!
Cheers!
