### ISSUE TITLE
Chrome extension sidebar sometimes closes right after clicking the eye icon

### ISSUE THREAD

**Issue by telotortium** [karlicoss/promnesia#295]
Symptoms: clicking the eye icon, usually on a page where I actually have visits, seems to do nothing at first. If I click repeatedly and rapidly on the eye icon, I can see the sidebar flicker briefly into existence, but then is closed within milliseconds after opening.

Don't know yet how to reproduce - seems intermittent. Often if I refresh the page, the sidebar will stay open when I click on it.

**Comment by karlicoss** [comment]
Thanks for reporting! It actually happens sometimes for me in firefox as well, I've tried reproducing for a while, but seems very random unfortunately

**Comment by yoyurec** [comment]
Windows, Chrome, any Udemy cource detail page flicks ((
For ex. this one - https://www.udemy.com/course/javascript-bible/

**Comment by karlicoss** [comment]
ooh @yoyurec great one, it flickers for me as well, so 100% reproducible at least
I had a quick look at the extension console, and no obvious errors, so will need to properly debug though

**Comment by yoyurec** [comment]
If you click Eye button after refreshing the page (F5) and you'll be fast anought (about 1sec) to do it right before icon become green - you can see sidebar.
Also, with "Always show sidebar" extension option ON - works ok, b'cose it do enabling right on page load.
I can assume that something wrong with Udemy. Some scripts loads after ~1 sec and do conflicts with extension.

**Comment by yoyurec** [comment]
BTW, with "Always show sidebar" extension option ON - works ok. Something wrong with clicking icon / hotkey

**Comment by yoyurec** [comment]
Debugged `background.js`
Normal page:
```
onUpdated {status: 'loading'}
onUpdated {}
onUpdated {status: 'complete'}
requesting! ..url..
```
Issue page:
```
onUpdated {status: 'loading'}
onUpdated {}
onUpdated {status: 'complete'}
requesting! ..url..
onUpdated {status: 'loading'}
onUpdated {status: 'complete'}
requesting! ..url..
```

**Comment by yoyurec** [comment]
> Please be aware `chrome.tabs.onUpdated` will also fired for iframes, if a page contains many iframes, each completed iframe will trigger the event though you have checked `changeInfo.status`. Use `chrome.webNavigation.onCompleted`

https://stackoverflow.com/a/68699443

**Comment by yoyurec** [comment]
Ta-daaa! 🐱‍👤
https://github.com/karlicoss/promnesia/pull/303

**Comment by karlicoss** [comment]
A super reliable way to reproduce for me
- go to https://docs.python.org/3/tutorial/index.html
- click on any link
- after that sidebar will flicker and won't open
- if you put a breakpoint inside `chrome.runtime.onMessage.addListener` in sidebar.js, you'll see it trigger twice when you press the extension button (this is wahat causes flickering, it toggles it twice so it shows then hides immediately)

Doesn't work 100% but triggers super often
I imagine it doesn't have to do with python site itself, it's just fast enough for this to manifest often

**Comment by karlicoss** [comment]
I think this should be fixed with the new extension release
