### ISSUE TITLE
extension: support query parameter for search page

### ISSUE THREAD

**Issue by telotortium** [karlicoss/promnesia#321]
I'd like to be able to use a query parameter for the search page so that you can open a link to a particular search. For example, if I want to search my Promnesia database for "brain efficiency", I should just be able to open <chrome-extension://kdmegllpofldcpaclldkopnnjjljoiio/search.html?q=brain+efficiency>. This would immediately unlock 2 benefits:

- I could write an Emacs command to search Promnesia for a term directly from Emacs.
- Promnesia may be able to be used as a search engine in Chrome (chrome://settings/searchEngines).

**Comment by karlicoss** [comment]
great idea, especially about the search engine! also relevant to pagination https://github.com/karlicoss/promnesia/issues/296 , e.g. then it would be convenient to use with opening new tabs, going back to search results etc
