### ISSUE TITLE
CSS settings broken since 1.1.1 update

### ISSUE THREAD

**Issue by practik** [karlicoss/promnesia#324]
What the title says: Since I updated, my custom CSS settings no longer have any effect. They were minimal – just moving the sidebar to the left and making it a bit narrower – but not subtle, so it was immediately obvious that they're not working any more. I also tested with the CSS from issue #281 just to be sure, and it also did nothing.

I'm guessing that it was actually the design enhancements in 1.1.0 that caused the breakage, but I don't know because I went straight from 1.0.1 to 1.1.1.

Also, while testing, I got the message IF YOU SEE THIS PLEASE REPORT AS A BUG! in the style settings box. I was using undo and redo to switch between different CSS sets, when suddenly redo took me back several undo steps. Another undo deleted all the lines except the one that had just changed, and then the next undo (or maybe redo) triggered the bug message.

And last but not least, I'm running Promnesia on Firefox 100.0.1 with no backend.

**Comment by practik** [comment]
Hmm, actually I just played with it a little more and can trigger the bug message reliably as follows:
1. Select all CSS.
2. Paste over it.
3. Undo.
4. Redo.

**Comment by yoyurec** [comment]
> my custom CSS settings no longer have any effect

@practik  can you post your custom CSS here?

**Comment by yoyurec** [comment]
some selectors was changed, try this
```css
/* tweak sidebar position/size/style */
#promnesia-frame {
    --left: 1;
    --size: 25%;
}
```

**Comment by practik** [comment]
Ah, that explains it – I had

````
#promnesia-sidebar {
    --left: 1;
    --size: 20%;
}
````
Thanks!

**Comment by karlicoss** [comment]
hmm, this is kinda surprising, I'm pretty sure I've had a regression test for that https://github.com/karlicoss/promnesia/blob/8bfba57dcfa0100f7c2636050ff5becf4e2112f0/tests/end2end_test.py#L507
I'll try again when I get to my computer, I was really hoping it would all be backwards compatible

**Comment by practik** [comment]
Closing since @yoyurec 's suggestion fixed for me; feel free to reopen, @karlicoss , if needed.

**Comment by karlicoss** [comment]
ah yes, 1.1.0 was basically skipped, there was a hotfix straight after.
I'll take a look once I get to the computer, but in the meantime, have you
tried restarting Firefox? It was necessary for me for some reason, perhaps
I need some hook in the extension code to refresh on upgrade.

**Comment by practik** [comment]
> in the meantime, have you

Nope, haven't restarted Firefox since May! :-P

But seriously: Did you mean to post your comment on some other, more current issue?

**Comment by karlicoss** [comment]
@practik uhh, I actually replied that back in May, but somehow Github lost the reply and only posted now :exploding_head: 
Seems like other people had a similar issue https://twitter.com/obra/status/1579868822638428163
