### ISSUE TITLE
Regarding the "how did I get here?" feature

### ISSUE THREAD

**Issue by shunlog** [karlicoss/promnesia#336]
I saw [your demo](https://karlicoss.github.io/promnesia-demos/how_did_i_get_here.webm) and it strucks me how awkward the approach you show is. In fact, using promnesia like that doesn't seem to offer any advantage to just looking in the browser history. Have you thought about better ways to achieve this feature? Ideally, it should show the source page from which i followed a link to the current page, for each visit of the current page (if there is any source page).

**Comment by karlicoss** [comment]
Hi. Well, first of all, the advantage is that Promnesia unifies history across multiple data sources (although I guess you're right that this particular demo doesn't emphasize that).
Even if you ignore that, e.g. in Firefox the history view is very basic -- if you search for a URL there it doesn't have timestamps etc. You can only find exact URL, it would not be possible to show you the context (other urls you've been browsing at the time etc.).

I agree, ideally Promnesia would just display where did you come to page from. But there isn't really a good way to determine this automatically -- some browsers have a field like `from_visit` in their history database -- but it's not present for all browsers, not always set, and when set it only works with tabs inside the browser. E.g. if you opened a link from twitter app in browser, it won't be set. So it seems that ultimately the only reliable option is presenting the timeline view and letting the user decide where they came from?

Open to ideas though :)
