### ISSUE TITLE
Sidebar doesn't show up on firefox

### ISSUE THREAD

**Issue by cariosa** [karlicoss/promnesia#388]

**Comment by cariosa** [comment]
I just got to know that this is a browser extension error, as it's working fine on chromium browser. The browser extension doesn't  open the pop-up when it's clicked, and is colored grey. Only the settings page works fine when visited from about:addons.

**Comment by karlicoss** [comment]
Hey @newBonfire , can you please share which url has the issue? Or all of them? Which version of firefox are you using?
It definitely works in Firefox for me, although perhaps the latest version of addon released on 18 May somehow fixed your issue too so I didn't notice -- can you double check?

**Comment by cariosa** [comment]
It's working fine for sometime now, maybe one of the updates fixed that issue.
