### ISSUE TITLE
fastapi/pydantic breaking versions

### ISSUE THREAD

**Issue by purarue** [karlicoss/promnesia#405]
pydantic had a breaking v2.0 change a few months ago, which fastapi upgraded to in 0.100.0

can see the releases here: https://github.com/tiangolo/fastapi/releases

so I think the versions in setup py should be something like `pip install -U 'fastapi<0.100.0' 'pydantic<2.0.0'`

Can make a PR if that seems reasonable, not sure if you want to migrate right now (doesnt seem too hard), but heres the guide for that

https://docs.pydantic.dev/2.0/migration/

and a tool to help migrate https://github.com/pydantic/bump-pydantic

**Comment by purarue** [comment]
Ah nevermind, I just saw [479603e](https://github.com/karlicoss/promnesia/commit/479603e94c1c65710fd8559664594659e276302a), was just putting this here as a warning

**Comment by karlicoss** [comment]
Thanks! Looks like all good now, at least CI is passing with `fastapi==0.101.1,,pydantic==2.3.0,pydantic_core==2.6.3`
