### ISSUE TITLE
server: systemd doesn't detect executable when `promnesia` isn't in PATH

### ISSUE THREAD

**Issue by ryanwwest** [karlicoss/promnesia#433]
Probably a dumb question, but I thought I followed the instructions on macos to install promnesia via `pip3 install promnesia` and things are running fine with `python3 -m pip promnesia serve`. But I don't have a `promnesia` executable in `$PATH`, is there an extra step to take to do this? This also means I can't run `install-server` since that requires running an executable file - I currently get this error I think because it can't find promnesia within python:

```
rw@:~$ sudo python3 -m promnesia install-server
Password:
[INFO    2023-12-15 23:36:18 promnesia __main__.py:383] CLI args: Namespace(mode='install-server', name='com.github.karlicoss.promnesia', host='0.0.0.0', port='13131', quiet=False, db=PosixPath('/Users/rw/Library/Application Support/promnesia/promnesia.sqlite'), timezone=<DstTzInfo 'America/Chicago' LMT-1 day, 18:09:00 STD>)
Writing launch script to /Users/rw/Library/LaunchAgents/com.github.karlicoss.promnesia.plist
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/rw/Library/Python/3.11/lib/python/site-packages/promnesia/__main__.py", line 422, in <module>
    main()
  File "/Users/rw/Library/Python/3.11/lib/python/site-packages/promnesia/__main__.py", line 413, in main
    install_server.install(args)
  File "/Users/rw/Library/Python/3.11/lib/python/site-packages/promnesia/misc/install_server.py", line 123, in install
    exe = distutils.spawn.find_executable('promnesia'); assert exe is not None
                                                               ^^^^^^^^^^^^^^^
AssertionError
```

**Comment by karlicoss** [comment]
Hey, sorry -- just going through issues I missed before!
Yeah -- good point -- the code has changed now slightly, but I think the issue would still be present
https://github.com/karlicoss/promnesia/blob/b08db7c2d0f8977ef75d3a87452bf880f0f31552/src/promnesia/misc/install_server.py#L120

I think the right way would be to switch it to use `sys.executable -m promnesia ...` instead -- so it would be able to find it regardless precence in PATH. I'll try to fix it tomorrow

**Comment by karlicoss** [comment]
Should be fixed -- released a new version on pypi as well!
