### ISSUE TITLE
Help with creating your own config.py

### ISSUE THREAD

**Issue by AtomicNess123** [karlicoss/promnesia#74]
Hi, excellent tool.
I would appreciate more indications for those who are not programmers. For instance "create your own config cp config.py.example config.py, edit config.py, and configure existing or custom sources". How do I go about creating my own file? WHat sources in which format to add to the file? If you could give me an example, it would be great. Thanks.

**Comment by AtomicNess123** [comment]
I have now managed to add the sources. My only question now is "the server promnesia serve --db /path/to/database". What is the database? Thanks!

**Comment by karlicoss** [comment]
@Gahamelas hi, it would be created in `OUTPUT_DIR` after your run `promnesia index`!
For example in case of [https://github.com/karlicoss/promnesia/blob/master/config.py.example#L4](example config), it would be `/tmp/promnesia.sqlite`.

I'll respond to the rest later today!

**Comment by karlicoss** [comment]
@Gahamelas Glad that you like the tool and thanks for trying and creating the issues, this will help me improve the docs!

I admit it's a bit confusing (and not just for non-programmers!), it's been under heavy development, so I'm only starting to document :)

Thanks for your suggestion, I've added a longer example config and added more comments! 

If you want to comment/review and think there are any obvious improvements you can do it here: https://github.com/karlicoss/promnesia/pull/76/files, all feedback welcome! And you can check it out [here](https://github.com/karlicoss/promnesia/tree/update-doc#extended-backend-setup).

**Comment by AtomicNess123** [comment]
Thank you!

**Comment by AtomicNess123** [comment]
BTW, I just found [ripgrep-all](https://github.com/phiresky/ripgrep-all) package. Includes searches within ZIP and PDF. Do you think it could be replaced in your function to look within PDF too?

**Comment by karlicoss** [comment]
@Gahamelas hey, not sure if you commented to the wrong project?

**Comment by AtomicNess123** [comment]
Thanks. Sorry about the misplacements.

**Comment by karlicoss** [comment]
Closing for now, since added lots of docs since.. But feel free to reopen if you need to!

**Comment by AtomicNess123** [comment]
Excellent. Doc in which project?
