### ISSUE TITLE
Custom sources

### ISSUE THREAD

**Issue by AtomicNess123** [karlicoss/promnesia#75]
You mentioned: 

> data exports from online services: Reddit/Twitter/Hackernews/Telegram/Messenger/Hypothesis/Pocket/Instapaper, etc

In which format can the sources be? In your config.py example you wrote

```
SOURCES = [
    Source(
        auto.index,
        # just some arbitrary directory with html files
```

But could these sources be ORG files or any text file?
Thanks, 
GM

**Comment by karlicoss** [comment]
- for Telegram/Twitter/Messenger/Hypothesis/Pocket/Instapaper --  added a relevant comment in your [other issue](https://github.com/karlicoss/promnesia/issues/74#issuecomment-622107407), the example doc contains them. 
   In most cases, it uses another package, [HPI](https://github.com/karlicoss/HPI) for the data. So please let me know is you can follow HPI documentation! 
- for Reddit, it's using the output of [rexport](https://github.com/karlicoss/rexport). But I will switch it to HPI too (that makes it easier to configure)

- for `auto.index` -- yes, these can be in pretty much [anything that's plaintext](https://github.com/karlicoss/promnesia/blob/66cce4013559aa10fbda20ca5509a3fcbbbb6955/src/promnesia/sources/auto.py#L129-L144), including org-mode files!

  One caveat, you might need extra libraries to parse org-mode or HTML or Mardown.
  You can see the full list [here](https://github.com/karlicoss/promnesia/blob/66cce4013559aa10fbda20ca5509a3fcbbbb6955/setup.py#L48-L85).

  So in case of org, you'll need to do `pip3 install --user "promnesia[org]"`.
  For markdown, `pip3 install --user "promensia[markdown]"`, etc.

  The easiest is just to install all of them (if you don't mind), I'll add support for `promnesia[all]` I guess.

Let me know if something's unclear!

**Comment by AtomicNess123** [comment]
Thanks a lot. Do you think that memacs or orger could do the trick by converting all the data to org? Then it could be read by your package?

**Comment by karlicoss** [comment]
Yes, absolutely, if you run it against Memacs/Orger outputs it should work!
The main benefit of using a special module instead of just org-mode output is that you can get cleaner link extraction, permalinks, that sort of thing. Whereas if you are processing org-mode pretty much the only thing you can do without some specific knowledge about your data source is to extract the links and use the outline.
But for the most part it should be similar! And easier to setup perhaps.

**Comment by AtomicNess123** [comment]
Thanks, your response goes to the point of what I was asking. So, if I understand correctly, your module Promnesia would work better with those tools you describe above for each service (Twitter, Telegram, etc.) than with the org output extracted with Orger or Memacs. My question is, if you want to have evens appearing on your Emacs agenda as well, then you would have to have all these tools at work (Memacs and all those). How do you manage all this? Would the info not be duplicated (having org files created by Memacs, plus the files created with Promnesia for the same apps? What is your pipeline? Would be good to know how you have set up everything.

**Comment by karlicoss** [comment]
>  your module Promnesia would work better with those tools you describe above for each service (Twitter, Telegram, etc.) than with the org output extracted with Orger or Memacs.

Yep, correct! But again, I think for the most part I think using org-mode as input should be fine.

> Would the info not be duplicated (having org files created by Memacs, plus the files created with Promnesia for the same apps?

Yep, good point! Basically for me the duplication happens in two places. I'll show with [hypothes.is](https://hypothes.is) as an example:

- Orger, which generates org-mode for me, easy to browse in my Emacs https://github.com/karlicoss/orger/blob/master/modules/hypothesis.py
- promnesia module, which processes it for the promnesia database https://github.com/karlicoss/promnesia/blob/master/src/promnesia/sources/hypothesis.py

As you can see both scripts are pretty short, so I think that chances of data going out of sync are pretty low. That is thanks to both of them using [HPI](https://github.com/karlicoss/HPI#readme), which hides the details of data parsing and deserialization.

> What is your pipeline?

I've started putting up a diagram [here](https://beepb00p.xyz/myinfra.html). It's a bit chaotic, but maybe gives some idea how I've got things set up :)

**Comment by AtomicNess123** [comment]
Impressive management of your virtual life. Hands down. The hypothesis data processed with Orger is the one going to emacs, while the one processed with Promnesia goes to browser. So no conflict there, as I see. BTW, I noticed you are not using memacs at all. What are you replacing it with? Thanks!

**Comment by karlicoss** [comment]
> I noticed you are not using memacs at all

Yep, I'm using [orger](https://github.com/karlicoss/orger) instead of memacs. There is no good reason, mostly because I only discovered Memacs after working on Orger, but I think they should be quite similar. I've been meaning to do a more detailed comparison, but haven't had time yet. Ideally would be great to cooperate and just merge them in a single tool, but haven't had time to work on it yet either :( If you check out both, please share your thoughts, I'd be keen to know!

**Comment by AtomicNess123** [comment]
Thanks for your answers!
